### ISSUE TITLE
Invalid pluralization for todo

### ISSUE THREAD

**Issue by olivergierke** [atteo/evo-inflector#5]
```java
assertThat(English.plural("todo"), is("todos"));
```

This one fails as the value returned is `todoes`.

**Comment by abhiaiyer91** [comment]
Hi there! My name is Abhi from a company called Prisma. We use this package to pluralize data types and our users rely on these types in their applications. With this change we have several schemas out there that we generated models based on the word 'Todo' -> 'Todoes'.

For example for a given type `Todo`, we generate crud operations like `createTodoes`, `updateTodoes`. 

With this change I'm afraid we have broken users or at least caused some friction in upgrading to newer versions of our product. Do you have any recommendations for us?

**Comment by sentinelt** [comment]
First, you can simply stick to the older version of this library. If the users complain about pluralization of some words then you can advise them to override the version to the newer one. This will work very well because there are hardly any other changes in this library than the ones fixing pluralization of some words.

Also the opposite is true. You can upgrade the evo-inflector version informing users about possible compatibility issues and possible workaround.

Also note that from the evo-inflector point of view, changes in pluralization is not an API change. Such changes can and will happen between minor versions of this library. The way you use the library amplifies the impact of the changes and that is why you need to upgrade the version with care.
